### ISSUE TITLE
Anti easy cheat flags handheld companion 

### ISSUE THREAD

**Issue by SYPHON313** [Valkirie/ControllerService#226]
Anti easy cheat has flagged handheld companion software as cheating and blocks the game if it's open. So as a result I can't use gyro with my onexplayer.  Do you have a work around for this?

**Comment by CasperH2O** [comment]
Hey @SYPHON313 thanks for letting us know, this is an unfortunate problem. 

Can you share what this looks like, is there a pop up, notification etc? Do you have a screenshot? Can you share the version number of Easy Anti Cheat and Handheld Companion used?

**Comment by CasperH2O** [comment]
Another question @SYPHON313 in the profile global setting, do you have the tick for "Translates XInput call to DirectInput calls" enabled? This causes issues with anti cheat software.

**Comment by SYPHON313** [comment]
No the xinput calls is not selected. Right now I'm on the default control companion profile. It doesn't matter what profile I select as long as the program is open it nothing works
![IMG_20220815_080836](https://user-images.githubusercontent.com/111252266/184632534-e192750a-0ac9-4f29-bcb9-35da56e6adea.jpg)

**Comment by CasperH2O** [comment]
As discussed on Discord, I searched around the web, other players and developers have reported that the company and support of EAC is pretty much impossible to work with, not giving any information or working with people to prevent false positives. Which is kind of ironic because they themselves work with anti virus software suppliers to have themselves whitelisted, but it's apparently not an option for us. 

Also, looking at it from their perspective, Handheld Companion is (currently) an unsigned open source application that can be forked by anyone and adjusted accordingly. No reason to assume someone could not use it for cheating purposes. Hell, maybe motion control aiming and flickstick could be considered a form of aim assist. 😅 

@SYPHON313  I realize this is not helping you in any way and I regret that, but it's pretty much out of our hands. Closing this issue as a won't fix.
